package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/Allan-Nava/pqprobe/internal/verdict"
)

// The generator behind docs/compatibility.md (PQ-78). It lives in a test file
// for the same reason the schema generator does: the page is a gate, not a
// feature, and nothing in the shipped binary should walk its own source.

type apiName struct {
	Kind string // func, type, const, var, method
	Name string
}

// compatFlags is the flag set the binary declares, which is the definition of
// "the flags" — a list typed into a page beside it is a list that disagrees.
func compatFlags() []*flag.Flag {
	fs, _ := newProbeFlags()
	var out []*flag.Flag
	fs.VisitAll(func(f *flag.Flag) { out = append(out, f) })
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func compatClasses() []verdict.Class { return verdict.Classes() }

// compatChecks reads the check names out of the verdict package itself. They
// are string literals on a struct field rather than a list anywhere, so the
// source is the list — and a check added without a row here would otherwise be
// a promise nobody made.
func compatChecks() []string {
	seen := map[string]bool{}
	// Both places that write one: most come from the verdict, three — egress,
	// resolver, net — are said once for the whole run by the CLI. A scan of the
	// verdict alone would have quietly under-promised those three.
	for _, dir := range []string{
		filepath.Join("..", "..", "internal", "verdict"),
		".",
	} {
		checksIn(dir, seen)
	}
	out := make([]string, 0, len(seen))
	for s := range seen {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

func checksIn(dir string, seen map[string]bool) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
		if err != nil {
			continue
		}
		ast.Inspect(f, func(n ast.Node) bool {
			kv, ok := n.(*ast.KeyValueExpr)
			if !ok {
				return true
			}
			if id, ok := kv.Key.(*ast.Ident); !ok || id.Name != "Check" {
				return true
			}
			if lit, ok := kv.Value.(*ast.BasicLit); ok && lit.Kind == token.STRING {
				if s, err := strconv.Unquote(lit.Value); err == nil && s != "" {
					seen[s] = true
				}
			}
			return true
		})
	}
}

// compatAPI is every exported name in pq/, which is the public Go surface: the
// thing a major release is *about* for an embedder.
func compatAPI() []apiName {
	var out []apiName
	dir := filepath.Join("..", "..", "pq")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
		if err != nil {
			continue
		}
		for _, d := range f.Decls {
			switch decl := d.(type) {
			case *ast.FuncDecl:
				if !decl.Name.IsExported() {
					continue
				}
				kind := "func"
				if decl.Recv != nil {
					kind = "method"
				}
				out = append(out, apiName{kind, decl.Name.Name})
			case *ast.GenDecl:
				for _, spec := range decl.Specs {
					switch sp := spec.(type) {
					case *ast.TypeSpec:
						if sp.Name.IsExported() {
							out = append(out, apiName{"type", sp.Name.Name})
						}
					case *ast.ValueSpec:
						for _, id := range sp.Names {
							if id.IsExported() {
								out = append(out, apiName{strings.ToLower(decl.Tok.String()), id.Name})
							}
						}
					}
				}
			}
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Name != out[j].Name {
			return out[i].Name < out[j].Name
		}
		return out[i].Kind < out[j].Kind
	})
	return out
}

var flagDefault = regexp.MustCompile(`\s+`)

// compatPage renders docs/compatibility.md.
func compatPage() (string, error) {
	var b strings.Builder

	b.WriteString(`<!-- GENERATED by go test ./cmd/pqprobe/ -update — do not edit by hand. -->

# Compatibility

What this tool promises not to break, and what it deliberately does not promise.
The lists are generated from the code they describe, so a flag, a class, a check
or an exported name that appears here is one the tool actually has.

## What the numbers mean

- **Patch** — a fix. Nothing in the lists below changes; an answer may get more
  correct, and a message may get clearer.
- **Minor** — something new: a flag, a profile, a class, a check, a finding, a
  field in a document, a metric. Everything already here keeps working and keeps
  meaning what it meant.
- **Major** — something below is removed or changes meaning. That is the only
  thing a major is for.

The document schema is versioned separately and moves on its own rules — see
[the schema page](schema.md). A minor release can add a field without touching
it; only a change of *shape* moves that number.

## Deliberately not stable

None of this is an oversight, and none of it will be treated as a break:

- **The prose.** A finding's ` + "`message`" + ` and ` + "`hint`" + `, the summary line, the text
  renderer's layout, the wording of an error. They are for people, and they get
  better. Read ` + "`check`" + `, ` + "`status`" + `, ` + "`class`" + `, ` + "`value`" + ` and ` + "`unit`" + ` instead — that
  is what they are for.
- **Anything under ` + "`internal/`" + `.** Not importable, by design: it is what lets
  those packages move.
- **` + "`contrib/`" + `.** Separate modules with their own dependencies and their own
  versions.
- **How many findings a run emits.** More appear as the tool learns to say more.
  The count is not a signal; the worst ` + "`status`" + ` is.
- **Timings, byte counts and measured sizes.** They describe the endpoint and the
  network, not this tool.

## Deprecation

A flag or a value that is going away keeps working for **at least two minor
releases** after it is first announced in the CHANGELOG, and says so on stderr
while it does. Removal is a major release. Nothing is ever repurposed: a name
that meant one thing does not come back meaning another.

An unknown value is always an error — never a quietly different run. That rule
has no deprecation period because it is what makes every other promise here
checkable.

`)

	fmt.Fprintf(&b, "## The flags\n\n")
	fmt.Fprintln(&b, "| Flag | Default |")
	fmt.Fprintln(&b, "|---|---|")
	for _, f := range compatFlags() {
		def := strings.TrimSpace(flagDefault.ReplaceAllString(f.DefValue, " "))
		if def == "" {
			def = "—"
		}
		fmt.Fprintf(&b, "| `--%s` | `%s` |\n", f.Name, def)
	}

	fmt.Fprintf(&b, "\n## The exit status\n\n")
	fmt.Fprintln(&b, "| Exit | Meaning |")
	fmt.Fprintln(&b, "|---|---|")
	fmt.Fprintln(&b, "| `0` | the probe ran — findings are output, not an error |")
	fmt.Fprintln(&b, "| `1` | `--exit-on` matched: a finding reached that status, or an endpoint landed in that class |")
	fmt.Fprintln(&b, "| `2` | the command line was wrong, or the target list could not be read |")
	fmt.Fprintln(&b, "\nThese three do not change without a major. A check that failed the pipeline on")
	fmt.Fprintln(&b, "every deviation is a check people route around, which is why exit 0 is the")
	fmt.Fprintln(&b, "answer whenever the probe ran at all.")

	fmt.Fprintf(&b, "\n## The classes\n\n")
	for _, c := range compatClasses() {
		fmt.Fprintf(&b, "- `%s` — %s\n", c, verdict.Describe(c))
	}
	fmt.Fprintln(&b, "\nNew classes appear in a minor release, as the tool learns to tell two")
	fmt.Fprintln(&b, "situations apart that it used to call one thing. Treat an unknown class as")
	fmt.Fprintln(&b, "unknown rather than as an error, and never as `ok`.")

	fmt.Fprintf(&b, "\n## The checks\n\n")
	checks := compatChecks()
	for i, c := range checks {
		if i > 0 {
			b.WriteString(" · ")
		}
		fmt.Fprintf(&b, "`%s`", c)
	}
	fmt.Fprintf(&b, "\n\nWhat each one says is in [Findings](findings.md). A name here keeps its\nmeaning; new ones arrive in a minor release.\n")

	fmt.Fprintf(&b, "\n## The Go API — `pq/`\n\n")
	fmt.Fprintln(&b, "| Kind | Name |")
	fmt.Fprintln(&b, "|---|---|")
	for _, n := range compatAPI() {
		fmt.Fprintf(&b, "| %s | `%s` |\n", n.Kind, n.Name)
	}
	fmt.Fprintln(&b, "\nStruct fields are part of this surface too: a field removed or renamed is a")
	fmt.Fprintln(&b, "major, a field added is a minor. `pq/` never exposes anything from `internal/`,")
	fmt.Fprintln(&b, "which is what lets the inside move while this stays still.")

	return b.String(), nil
}
