# Generated by scripts/brew.sh — do not edit by hand.
#
# The tap is this repository:
#
#   brew tap allan-nava/pqprobe https://github.com/Allan-Nava/pqprobe
#   brew install pqprobe
#
# It clones the tag and builds from source, so one formula covers macOS and
# Linux on Intel and ARM. Go is a build dependency and nothing else: pqprobe has
# no dependencies of its own.
class Pqprobe < Formula
  desc "Which classes of TLS client can still handshake with this endpoint"
  homepage "https://allan-nava.github.io/pqprobe/"
  url "https://github.com/Allan-Nava/pqprobe.git", tag: "v0.21.0"
  version "0.21.0"
  license "MIT"
  head "https://github.com/Allan-Nava/pqprobe.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pqprobe version")

    # A handshake needs the network, which a sandboxed test does not have. The
    # profile list is the part that proves the binary is the right one: it is
    # the capability classes this version was built with.
    assert_match "pq-preferred", shell_output("#{bin}/pqprobe profiles")
  end
end
