#!/bin/sh
# brew.sh — render the Homebrew formula, and keep it from going stale.
#
#   scripts/brew.sh render    print the formula for the version CHANGELOG.md names
#   scripts/brew.sh write     write it to Formula/pqprobe.rb
#   scripts/brew.sh check     fail if the formula does not name that version
#
# The tap is this repository: `Formula/pqprobe.rb` here is all a tap needs, so
# there is no second repo to keep in step and no fine-grained token for a
# workflow to push with. `scripts/release.sh` renders it *inside* the version
# commit, which is also why nothing in CI ever commits: every commit here is a
# version, and a bot commit bumping a formula would not be one.
#
# The formula clones the tag rather than fetching a tarball. A tarball needs its
# sha256, and that cannot be known while rendering the file that will be part of
# the very commit the tag points at — a chicken and egg the tag sidesteps. It
# also builds from source, so one formula covers macOS and Linux, Intel and ARM,
# without six bottles to publish.
#
# The version is deliberately *not* stated: `brew audit` rejects it as
# "redundant with version scanned from URL", since Homebrew reads it off the
# tag. That was found by running `brew audit` rather than by reasoning about it,
# which is also why the Brew workflow exists.
#
# `check` is a CI gate for the reason a stale formula is worse than a missing
# one: `brew install` reads whatever it says, so a formula left at v0.2.0 after
# v0.3.0 shipped installs the old binary and looks like it worked.
#
# POSIX sh and awk only. CHANGELOG_FILE and FORMULA_FILE point at fixtures.

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
changelog="${CHANGELOG_FILE:-$root/CHANGELOG.md}"
formula="${FORMULA_FILE:-$root/Formula/pqprobe.rb}"
mode="${1:-check}"

[ -f "$changelog" ] || { echo "brew.sh: no such file: $changelog" >&2; exit 2; }

# The newest released version in the changelog. [Unreleased] is not a version a
# formula can install, so it is an error rather than a formula nobody can use.
version() {
	v=$(awk '/^## \[/ {
		i = index($0, "["); j = index($0, "]")
		print substr($0, i + 1, j - i - 1); exit
	}' "$changelog")
	case "$v" in
	'') echo "brew.sh: CHANGELOG.md has no version section" >&2; exit 1 ;;
	[Uu]nreleased)
		echo "brew.sh: the newest CHANGELOG section is [Unreleased] — render the formula from a released version" >&2
		exit 1
		;;
	esac
	printf '%s\n' "$v"
}

render() {
	v=$(version)
	cat <<RUBY
# Generated by scripts/brew.sh — do not edit by hand.
#
# The tap is this repository:
#
#   brew tap allan-nava/pqprobe https://github.com/Allan-Nava/pqprobe
#   brew install pqprobe
#
# It clones the tag and builds from source, so one formula covers macOS and
# Linux on Intel and ARM. Go is a build dependency and nothing else: pqprobe has
# no dependencies of its own.
class Pqprobe < Formula
  desc "Which classes of TLS client can still handshake with this endpoint"
  homepage "https://allan-nava.github.io/pqprobe/"
  url "https://github.com/Allan-Nava/pqprobe.git", tag: "v$v"
  license "MIT"
  head "https://github.com/Allan-Nava/pqprobe.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pqprobe version")

    # A handshake needs the network, which a sandboxed test does not have. The
    # profile list is the part that proves the binary is the right one: it is
    # the capability classes this version was built with.
    assert_match "pq-preferred", shell_output("#{bin}/pqprobe profiles")
  end
end
RUBY
}

case "$mode" in
render)
	render
	;;
write)
	v=$(version)
	mkdir -p "$(dirname -- "$formula")"
	render > "$formula"
	printf 'wrote %s for v%s\n' "${formula#"$root/"}" "$v"
	;;
check)
	v=$(version)
	if [ ! -f "$formula" ]; then
		echo "brew.sh: $formula does not exist — run scripts/brew.sh write" >&2
		exit 1
	fi
	if ! grep -q "tag: \"v$v\"" "$formula"; then
		echo "brew.sh: the formula does not name v$v:" >&2
		grep -n 'tag:\|^  version' "$formula" >&2 || :
		echo "  run scripts/brew.sh write and commit the result" >&2
		exit 1
	fi
	if ! render | diff -u "$formula" - >/dev/null; then
		echo "brew.sh: Formula/pqprobe.rb differs from what brew.sh renders:" >&2
		render | diff -u "$formula" - >&2 || :
		echo "  it is generated — run scripts/brew.sh write" >&2
		exit 1
	fi
	printf 'formula OK — Formula/pqprobe.rb installs v%s\n' "$v"
	;;
*)
	echo "usage: scripts/brew.sh [render|write|check]" >&2
	exit 2
	;;
esac
