#!/bin/sh
# seo.sh — generate the crawler-facing files for the docs site, and gate them.
#
#   scripts/seo.sh render    write sitemap.xml, robots.txt and llms.txt
#   scripts/seo.sh check     fail if they disagree with the page (CI gate)
#
# Everything here fails *silently* by nature: a sitemap naming an old URL, a
# canonical that drifted from the About box, a JSON-LD block truncated by an
# edit. The page still renders, and the only symptom is that it quietly stops
# being found. So the files are generated from the page rather than maintained
# beside it, and the disagreement is a build failure.
#
# Where robots.txt actually gets read, which took looking rather than assuming:
# this is a GitHub *project* page, so ours lands at /pqprobe/robots.txt and
# crawlers only read the one at the host root, https://allan-nava.github.io/
# robots.txt. That belongs to the Allan-Nava.github.io repository — and that
# repository already generates its per-project `Sitemap:` lines from a daily
# sync (robots-sync.yml) which enumerates the owner's non-fork repos with Pages
# enabled and keeps the ones whose /<repo>/sitemap.xml answers **200**.
#
# So the mechanism is: ship a sitemap that answers 200, and the host root picks
# it up by itself. Nothing to declare anywhere, no list to maintain — which is
# also why 28 of that owner's live Pages sites are absent from it: they ship no
# sitemap. Ours stays the local source of truth this gate checks against, and
# becomes the served one the day a custom domain moves this off the shared host.
#
# POSIX sh and awk only. SEO_DIR and SEO_VERSION point at a fixture.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
dir="${SEO_DIR:-$root/docs}"
mode="${1:-check}"

html="$dir/index.html"
[ -f "$html" ] || { echo "seo.sh: no such file: $html" >&2; exit 2; }

version="${SEO_VERSION:-}"
if [ -z "$version" ]; then
	version=$(CHANGELOG_FILE="${CHANGELOG_FILE:-$root/CHANGELOG.md}" sh "$root/scripts/version.sh" current)
fi

# attr <regex> — the href/content of the first line matching regex.
attr() {
	awk -v pat="$1" '
		$0 ~ pat {
			for (k = 1; k <= 2; k++) {
				key = (k == 1) ? "href=\"" : "content=\""
				i = index($0, key)
				if (i) {
					r = substr($0, i + length(key))
					j = index(r, "\"")
					print substr(r, 1, j - 1)
					exit
				}
			}
		}
	' "$html"
}

canonical=$(attr 'rel="canonical"')
[ -n "$canonical" ] || { echo "seo.sh: the page has no rel=canonical" >&2; exit 1; }
case "$canonical" in
*/) ;;
*) canonical="$canonical/" ;;
esac

title=$(awk -F'[<>]' '/<title>/ { print $3; exit }' "$html")
desc=$(attr 'name="description"')

render() {
	today=$(date +%Y-%m-%d)

	cat > "$dir/sitemap.xml" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/seo.sh — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>$canonical</loc>
    <lastmod>$today</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
XML

	cat > "$dir/robots.txt" <<TXT
# Generated by scripts/seo.sh — do not edit by hand.
#
# On a GitHub project page this file sits at /pqprobe/robots.txt, and crawlers
# read only the host root's — https://allan-nava.github.io/robots.txt, which
# generates its Sitemap: lines from the sitemaps that answer 200, this one
# included. This file is the local source of truth the SEO gate checks against,
# and the one actually served if this ever moves to a domain of its own.
User-agent: *
Allow: /
Disallow:

Sitemap: ${canonical}sitemap.xml
TXT

	cat > "$dir/llms.txt" <<TXT
# pqprobe $version

> $desc

Documentation: $canonical
Source: https://github.com/Allan-Nava/pqprobe

## What it is

pqprobe dials one TLS endpoint with several deliberately different client shapes
and reports which classes of client can still complete a handshake with it, now
that post-quantum key exchange (hybrid ML-KEM, X25519MLKEM768) is on by default
in browsers and CDNs. One static Go binary, zero dependencies, no application
data ever sent: it handshakes and closes.

## The distinction it exists for

A peer that answers a post-quantum ClientHello with a TLS **alert** has parsed
it and declined a group: a policy, a pinned group list, a negotiation that
worked. A peer that **resets, times out or vanishes** choked on the hello
itself, and is broken for every client that so much as offers ML-KEM — however
happy that client would have been with X25519. Only the second is an outage
waiting for a CDN to flip a default, and no other tool reports the difference.

## Classes

- pq-ready — hybrid key exchange works, including for a client that requires it
- pq-capable — ML-KEM is negotiated when offered, but a post-quantum-only client did not connect
- pq-blind — no post-quantum support; capable clients still connect on a classical group
- pq-refusing — capable clients are refused with an alert while classical ones connect
- pq-intolerant — capable clients are cut off while classical ones connect
- no-tls13 — TLS 1.2 is the ceiling, so post-quantum key exchange is out of reach
- mtls-required — the peer wants a client certificate; not a grade
- unreachable — nothing answered; not a grade
- tls-broken — the port answered and no profile completed a handshake; not a grade

## Pages

- ${canonical} — everything: classes, profiles, install, flags, findings, scope
- https://github.com/Allan-Nava/pqprobe/blob/main/INTENT.md — why it exists, and what is deliberately out of scope
- https://github.com/Allan-Nava/pqprobe/blob/main/BACKLOG.md — planned work
- https://github.com/Allan-Nava/pqprobe/blob/main/CHANGELOG.md — what changed, per tagged release

## Not

Not a TLS scanner (testssl.sh, sslyze), not a certificate monitor (checkfleet),
not a load generator (crowdsim), not a fingerprinting tool: profiles are
capability classes, and Go's crypto/tls cannot reproduce a browser ClientHello.
TXT

	printf 'wrote sitemap.xml, robots.txt and llms.txt for %s\n' "$canonical"
}

check() {
	bad=0
	err() { printf 'seo.sh: %s\n' "$1" >&2; bad=$((bad + 1)); }

	# The tags a search result is built from. Losing one is invisible on the page.
	for pat in 'name="description"' 'name="robots"' 'rel="canonical"' 'property="og:image"' 'property="og:title"'; do
		grep -q "$pat" "$html" || err "the page has no $pat"
	done
	[ -n "$title" ] || err "the page has no <title>"
	[ -n "$desc" ] || err "the page has no description"

	# A description outside this range is either truncated in a result or too
	# thin to say anything.
	n=$(printf '%s' "$desc" | wc -c | tr -d ' ')
	if [ -n "$desc" ] && { [ "$n" -lt 70 ] || [ "$n" -gt 320 ]; }; then
		err "the description is $n characters; aim for 70-320"
	fi

	# JSON-LD: present, naming this page, and not truncated. Braces are checked
	# rather than parsed, because there is no JSON parser here and truncation is
	# the failure that actually happens.
	if ! grep -q 'application/ld+json' "$html"; then
		err "the page carries no JSON-LD"
	else
		ld=$(awk '/application\/ld\+json/ { inside = 1; next } /<\/script>/ { inside = 0 } inside' "$html")
		opens=$(printf '%s' "$ld" | tr -cd '{' | wc -c | tr -d ' ')
		closes=$(printf '%s' "$ld" | tr -cd '}' | wc -c | tr -d ' ')
		[ "$opens" -gt 0 ] || err "the JSON-LD block is empty"
		[ "$opens" = "$closes" ] || err "the JSON-LD braces do not balance ($opens open, $closes closed) — an edit truncated it"
		printf '%s' "$ld" | grep -q "$canonical" || err "the JSON-LD does not name $canonical"
	fi

	for f in sitemap.xml robots.txt llms.txt; do
		[ -f "$dir/$f" ] || { err "docs/$f is missing — run scripts/seo.sh render"; continue; }
	done
	[ -f "$dir/sitemap.xml" ] && { grep -q "<loc>$canonical</loc>" "$dir/sitemap.xml" ||
		err "sitemap.xml does not name $canonical — run scripts/seo.sh render"; }
	# Every URL in the sitemap needs a file behind it. Found while porting this
	# gate to segcheck, whose first sitemap listed a .html that 404s because
	# Pages serves docs/ as committed. A declared URL with nothing behind it
	# wastes crawl budget on every crawl — the same reason the host root only
	# lists sitemaps that answer 200.
	if [ -f "$dir/sitemap.xml" ]; then
		awk -F'[<>]' '/<loc>/ { print $3 }' "$dir/sitemap.xml" | while IFS= read -r loc; do
			rel=${loc#"$canonical"}
			case "$rel" in
			"" ) path="index.html" ;;
			*/ ) path="$rel/index.html" ;;
			* )  path="$rel" ;;
			esac
			[ -e "$dir/$path" ] || printf '%s -> %s\n' "$loc" "$path"
		done > "$dir/.seo-missing.$$"
		if [ -s "$dir/.seo-missing.$$" ]; then
			while IFS= read -r line; do
				err "the sitemap declares a URL with no file behind it: $line"
			done < "$dir/.seo-missing.$$"
		fi
		rm -f "$dir/.seo-missing.$$"
	fi

	[ -f "$dir/robots.txt" ] && { grep -q "Sitemap: ${canonical}sitemap.xml" "$dir/robots.txt" ||
		err "robots.txt does not point at ${canonical}sitemap.xml"; }
	[ -f "$dir/llms.txt" ] && { grep -q "pqprobe $version" "$dir/llms.txt" ||
		err "llms.txt does not describe $version — run scripts/seo.sh render"; }

	if [ "$bad" -gt 0 ]; then
		printf '\n%d SEO problem(s)\n' "$bad" >&2
		exit 1
	fi
	printf 'seo OK — %s, %d-character description, sitemap and llms.txt in step\n' "$canonical" "$n"
}

case "$mode" in
render) render ;;
check)  check ;;
*)
	echo "usage: scripts/seo.sh [render|check]" >&2
	exit 2
	;;
esac
